//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9,8,36")]
        public string ColCellCountArray {
            get {
                return ((string)(this["ColCellCountArray"]));
            }
            set {
                this["ColCellCountArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SICXEASM.exe")]
        public string ASMExe {
            get {
                return ((string)(this["ASMExe"]));
            }
            set {
                this["ASMExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SICSIM.exe")]
        public string SIMExe {
            get {
                return ((string)(this["SIMExe"]));
            }
            set {
                this["SIMExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASMArgs {
            get {
                return ((string)(this["ASMArgs"]));
            }
            set {
                this["ASMArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SIMArgs {
            get {
                return ((string)(this["SIMArgs"]));
            }
            set {
                this["SIMArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASMInput {
            get {
                return ((string)(this["ASMInput"]));
            }
            set {
                this["ASMInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s\r\nr\r\nd r\r\nd 1000-1140")]
        public string SIMInput {
            get {
                return ((string)(this["SIMInput"]));
            }
            set {
                this["SIMInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rename.bat")]
        public string ASMScript {
            get {
                return ((string)(this["ASMScript"]));
            }
            set {
                this["ASMScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\s(a(d(d[r]?)|nd)|c(lear|o(m(p[r]?)))|d(i(v[r]?))|end|j(eq|gt|lt|sub)?|l(d(a|b|ch" +
            "|l|s|t|x))|m(u(l[r]?))|or|r(d|mo|sub)|s(h(i(f(t[lr])))|t(a(rt)?|b|ch|l|s|t|x)|u(" +
            "b[r]?))|t(d|i(x[r]?))|wd)\\s")]
        public string SyntaxRegex {
            get {
                return ((string)(this["SyntaxRegex"]));
            }
            set {
                this["SyntaxRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=\\n)[^\\s]+(?=\\s)")]
        public string LabelRegex {
            get {
                return ((string)(this["LabelRegex"]));
            }
            set {
                this["LabelRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=[\\s,])([axbflsti]|ch|xr)(?=[\\s,])")]
        public string RegisterRegex {
            get {
                return ((string)(this["RegisterRegex"]));
            }
            set {
                this["RegisterRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=[\\s#])([-0-9]+)(?=[\\s,])")]
        public string IntegerRegex {
            get {
                return ((string)(this["IntegerRegex"]));
            }
            set {
                this["IntegerRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=[\\s#])([-0-9]*\\.[0-9]+)(?=[\\s,])")]
        public string DecRegex {
            get {
                return ((string)(this["DecRegex"]));
            }
            set {
                this["DecRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\s(word|byte|res[bw])\\s")]
        public string DataTypeRegex {
            get {
                return ((string)(this["DataTypeRegex"]));
            }
            set {
                this["DataTypeRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color SyntaxColor {
            get {
                return ((global::System.Drawing.Color)(this["SyntaxColor"]));
            }
            set {
                this["SyntaxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color LabelColor {
            get {
                return ((global::System.Drawing.Color)(this["LabelColor"]));
            }
            set {
                this["LabelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color RegisterColor {
            get {
                return ((global::System.Drawing.Color)(this["RegisterColor"]));
            }
            set {
                this["RegisterColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color IntegerColor {
            get {
                return ((global::System.Drawing.Color)(this["IntegerColor"]));
            }
            set {
                this["IntegerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlueViolet")]
        public global::System.Drawing.Color DecColor {
            get {
                return ((global::System.Drawing.Color)(this["DecColor"]));
            }
            set {
                this["DecColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color DataTypeColor {
            get {
                return ((global::System.Drawing.Color)(this["DataTypeColor"]));
            }
            set {
                this["DataTypeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CodeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeBackColor"]));
            }
            set {
                this["CodeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CodeForeColor {
            get {
                return ((global::System.Drawing.Color)(this["CodeForeColor"]));
            }
            set {
                this["CodeForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ConsoleFontSize {
            get {
                return ((int)(this["ConsoleFontSize"]));
            }
            set {
                this["ConsoleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ConsoleBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ConsoleBackColor"]));
            }
            set {
                this["ConsoleBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ConsoleForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ConsoleForeColor"]));
            }
            set {
                this["ConsoleForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Crimson")]
        public global::System.Drawing.Color StringColor {
            get {
                return ((global::System.Drawing.Color)(this["StringColor"]));
            }
            set {
                this["StringColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=c)([\'][^\']+[\'])")]
        public string StringRegex {
            get {
                return ((string)(this["StringRegex"]));
            }
            set {
                this["StringRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color HexColor {
            get {
                return ((global::System.Drawing.Color)(this["HexColor"]));
            }
            set {
                this["HexColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=x)([\'][^\']+[\'])")]
        public string HexRegex {
            get {
                return ((string)(this["HexRegex"]));
            }
            set {
                this["HexRegex"] = value;
            }
        }
    }
}
